controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute


App\Controller\DataGeneratorController:
    resource: '../src/Controller/DataGeneratorController.php'
    type: annotation